version: '3'

services:
  mysql:
    image: mariadb
    ports:
    - "33066:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin_Passw0rd
      MYSQL_USER: feathersuser
      MYSQL_PASSWORD: feathers_Passw0rd
      MYSQL_DATABASE: feathers
